version: '3.4'

services:
  jaeger-agent:
    container_name: 'jaeger'
    image: jaegertracing/all-in-one:1.47
    networks:
      - jaeger-tracing
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - LOG_LEVEL=debug

networks:
  jaeger-tracing: